from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from fastapi import APIRouter, Depends
from fastapi.responses import FileResponse
from src.backend.auth import require_admin
from src.backend.db import get_recent_threats, get_blocklist
from src.config import PROJECT_ROOT
import time

router = APIRouter()
REPORTS_DIR = PROJECT_ROOT / "data" / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

@router.get("/api/reports/download")
async def download_report(current_user: dict = Depends(require_admin)):
    file_path = REPORTS_DIR / f"AegisNet_Audit_{int(time.time())}.pdf"
    
    doc = SimpleDocTemplate(str(file_path), pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []
    
    # Title
    elements.append(Paragraph("AegisNet Security Audit Report", styles['Title']))
    elements.append(Spacer(1, 12))
    
    # Summary
    threats = get_recent_threats(100)
    blocks = get_blocklist()
    
    elements.append(Paragraph(f"Generated by: {current_user['username']} ({current_user['role'].upper()})", styles['Normal']))
    elements.append(Paragraph(f"Total Recent Threats Logged: {len(threats)}", styles['Normal']))
    elements.append(Paragraph(f"Total Blocked IPs: {len(blocks)}", styles['Normal']))
    elements.append(Spacer(1, 24))
    
    # Blocklist Table
    elements.append(Paragraph("Currently Blocked IPs", styles['Heading2']))
    elements.append(Spacer(1, 12))
    
    table_data = [["IP Address", "Reason Blocked"]]
    for b in blocks[:15]: # Show top 15
        table_data.append([b['ip'], b['reason']])
        
    if len(table_data) > 1:
        t = Table(table_data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1e293b")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('BACKGROUND', (0,1), (-1,-1), colors.HexColor("#f8fafc")),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))
        elements.append(t)
    else:
        elements.append(Paragraph("No IPs currently blocked.", styles['Normal']))
        
    doc.build(elements)
    
    return FileResponse(path=file_path, filename="AegisNet_Audit_Report.pdf", media_type='application/pdf')
